Classifcation:  When our taget variable is a category. 
Binary_Classifcation: When target feature has only two categories in it. 
Multiclassifcation: When target feature has mor than two categories in it.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('diabetes.csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
data.shape

(768, 9)

In [4]:
data.Outcome.unique()

array([1, 0])

In [5]:
data.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

# Since we have two categories in OutCome: Binary Classification

In [6]:
X = data.drop('Outcome', axis=1)
y = data.Outcome

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [8]:
X_train.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
334,1,95,60,18,58,23.9,0.260,22
139,5,105,72,29,325,36.9,0.159,28
485,0,135,68,42,250,42.3,0.365,24
547,4,131,68,21,166,33.1,0.160,28
18,1,103,30,38,83,43.3,0.183,33

In [9]:
X_train.shape[0]

537

In [10]:
y_train

334    0
139    0
485    1
547    0
18     0
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 537, dtype: int64

In [11]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [12]:
log_reg.fit(X_train,y_train)

C:\Users\amazo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [13]:
log_reg.coef_

array([[ 0.05654379,  0.03558453, -0.01087781, -0.00179054, -0.00098901,
         0.10761167,  0.52393797,  0.03582561]])

In [14]:
log_reg.intercept_

array([-9.39074761])

In [15]:
y_pred_train= log_reg.predict(X_train)

In [16]:
y_pred_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0])

In [17]:
pd.DataFrame({'Origial_y':y_train, 'Predicted_y':y_pred_train})

     Origial_y  Predicted_y
334          0            0
139          0            0
485          1            0
547          0            0
18           0            0
..         ...          ...
71           0            0
106          0            0
270          1            1
435          1            1
102          0            0

[537 rows x 2 columns]

In [18]:
count=0
for orig,pred in zip(y_train, y_pred_train):
    if orig==pred:
        count+=1
accuracy = count/ X_train.shape[0] *100
accuracy

78.2122905027933

### Performance Evaluation of a classifier
   - Accuracy
   - Precision
   - Recall

In [19]:
from sklearn.metrics import ConfusionMatrixDisplay

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score, precision_score, recall_score, classification_report

In [21]:
confusion_matrix(y_train, y_pred_train)

array([[310,  39],
       [ 78, 110]])

In [22]:
accuracy_score(y_train, y_pred_train)

0.7821229050279329

In [23]:
precision_score(y_train, y_pred_train)

0.738255033557047

In [24]:
recall_score(y_train, y_pred_train)

0.5851063829787234

In [25]:
f1_score(y_train, y_pred_train)

0.6528189910979229

In [26]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84       349
           1       0.74      0.59      0.65       188

    accuracy                           0.78       537
   macro avg       0.77      0.74      0.75       537
weighted avg       0.78      0.78      0.78       537

https://www.google.com/search?q=precision+and+recall+and+f1+score&oq=preceiocn+and+recall&gs_lcrp=EgZjaHJvbWUqCQgEEAAYDRiABDIGCAAQRRg5MgkIARAAGA0YgAQyCQgCEAAYDRiABDIJCAMQABgNGIAEMgkIBBAAGA0YgAQyCQgFEAAYDRiABDIJCAYQABgNGIAEMgkIBxAAGA0YgAQyCQgIEAAYDRiABDIJCAkQABgNGIAE0gEINTY3N2owajeoAgiwAgHxBXk-uKbIJk1h&sourceid=chrome&ie=UTF-8

In [27]:
data.shape

(768, 9)

# Class Imbalance

In [28]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [29]:
class_0 = data[data.Outcome==0].sample(268)

In [30]:
class_1 = data[data.Outcome==1].sample(268)

In [31]:
class_0.shape

(268, 9)

In [32]:
class_1.shape

(268, 9)

In [33]:
new_data = pd.concat([class_0,class_1]).sample(536)

In [34]:
new_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
679,2,101,58,17,265,24.2,0.614,23,0
480,3,158,70,30,328,35.5,0.344,35,1
693,7,129,68,49,125,38.5,0.439,43,1
256,3,111,56,39,0,30.1,0.557,30,0
166,3,148,66,25,0,32.5,0.256,22,0
...,...,...,...,...,...,...,...,...,...
6,3,78,50,32,88,31.0,0.248,26,1
523,9,130,70,0,0,34.2,0.652,45,1
206,8,196,76,29,280,37.5,0.605,57,1
294,0,161,50,0,0,21.9,0.254,65,0
48,7,103,66,32,0,39.1,0.344,31,1

In [35]:
X_new = new_data.drop('Outcome',axis=1)
y_new = new_data.Outcome

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.30, random_state=42)

In [37]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [38]:
log_reg.fit(X_train,y_train)

C:\Users\amazo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [39]:
y_pred_train= log_reg.predict(X_train)

In [40]:
confusion_matrix(y_train,y_pred_train)

array([[142,  49],
       [ 48, 136]])

In [41]:
accuracy_score(y_train,y_pred_train)

0.7413333333333333

In [42]:
precision_score(y_train,y_pred_train)

0.7351351351351352

In [43]:
recall_score(y_train,y_pred_train)

0.7391304347826086

In [44]:
f1_score(y_train,y_pred_train)

0.7371273712737128

In [45]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.75      0.74      0.75       191
           1       0.74      0.74      0.74       184

    accuracy                           0.74       375
   macro avg       0.74      0.74      0.74       375
weighted avg       0.74      0.74      0.74       375

# SMOTE for Imbalanced Classification with Python

In [46]:
from imblearn.over_sampling import SMOTE

In [47]:
smote = SMOTE(sampling_strategy='auto', random_state=42)
X_sm, y_sm = smote.fit_resample(X, y)

In [48]:
y_sm.value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.30, random_state=42)

In [50]:
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

C:\Users\amazo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [51]:
y_pred_train= log_reg.predict(X_train)

In [52]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.72      0.77      0.75       351
           1       0.75      0.70      0.73       349

    accuracy                           0.74       700
   macro avg       0.74      0.74      0.74       700
weighted avg       0.74      0.74      0.74       700

In [54]:
y_pred_test = log_reg.predict(X_test)

In [55]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.75      0.76      0.76       149
           1       0.76      0.75      0.76       151

    accuracy                           0.76       300
   macro avg       0.76      0.76      0.76       300
weighted avg       0.76      0.76      0.76       300

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# -----------------------------
# TRAIN MODEL FUNCTION
# -----------------------------
@st.cache_resource

def train_model():
    data = pd.read_csv("diabetes.csv")

    X = data.drop("Outcome", axis=1)
    y = data["Outcome"]

    smote = SMOTE(random_state=42)
    X_sm, y_sm = smote.fit_resample(X, y)

    X_train, X_test, y_train, y_test = train_test_split(
        X_sm, y_sm, test_size=0.30, random_state=42
    )

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    return model


model = train_model()

# -----------------------------
# STREAMLIT UI
# -----------------------------

st.title("Diabetes Prediction App")
st.write("Enter patient details below to predict diabetes risk.")

pregnancies = st.number_input("Pregnancies", min_value=0, max_value=20, step=1)

Glucose = st.number_input("Glucose Level", min_value=0)

BloodPressure = st.number_input("Blood Pressure", min_value=0)

SkinThickness = st.number_input("Skin Thickness", min_value=0)

Insulin = st.number_input("Insulin Level", min_value=0)

BMI = st.number_input("BMI", min_value=0.0, format="%.2f")

DiabetesPedigreeFunction = st.number_input(
    "Diabetes Pedigree Function", min_value=0.0, format="%.4f"
)

Age = st.number_input("Age", min_value=1, max_value=120)


# -----------------------------
# PREDICTION BUTTON
# -----------------------------

if st.button("Predict Diabetes Risk"):

    input_data = np.array(
        [
            [
                pregnancies,
                Glucose,
                BloodPressure,
                SkinThickness,
                Insulin,
                BMI,
                DiabetesPedigreeFunction,
                Age,
            ]
        ]
    )

    prediction = model.predict(input_data)
    probability = model.predict_proba(input_data)[0][1]

    if prediction[0] == 1:
        st.error("High Risk of Diabetes")
    else:
        st.success("Low Risk of Diabetes")

    st.write(f"Prediction Confidence: {probability:.2f}")


st.markdown("---")
st.caption("Model: Logistic Regression trained with SMOTE-balanced dataset")